# Generated by Django 6.0.3 on 2026-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение объявления",
                null=True,
                upload_to="ads/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
